# Generated by Django 5.0 on 2023-12-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_thumbnail_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='date',
            new_name='upload_date',
        ),
        migrations.AddField(
            model_name='video',
            name='tag',
            field=models.ManyToManyField(blank=True, to='video.tag'),
        ),
    ]
